### PR TITLE
Adding search functionality to frontend

### PR DESCRIPTION
**Pull request by nofearOnline**
# Description
Adding search functionality to frontend

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
That was fast! Let’s see...

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Bummer,  it doesn’t seem like the frontend works. Let’s give it another try.

**Review by vanessa-cooper — APPROVED** [review]
Yay, it works!

**Comment by nofearOnline** [comment]
a. it was not fast
b. the frontend work(The pr check passed) but wasn't linted as expected

**Pull request merged**
